export const translation = {
  en: {
    header: "Playground",
    title1: "Your Name",
    title2: "Your Photo",
    header_text: "Play With Your Name",
    notename_text: "From 4-10 Characters",
    notenslogan_text: "From 8-35 Characters",
    slogan_text: "Craft with love, Shop with taste",
    button1_text: "Save & Download",
    button2_text: "Home",

    // image
    note1_crop: "* The photo size will affect the loading speed",
    note2_crop: "* Recommend files under 5MB",
    header_image: "Play With Your Image",
    button1_image: "Upload Image",
    button2_image: "Home",
    button1_image_crop: "Crop & Next",
    button2_image_crop: "Home",
    button3_image_crop: "Change Image",
    popup_edit: "EDIT MODE",
    popup1_edit: "Add Sticker",
    popup2_edit: "Delete Sticker",
    note1_edit: "* Face recognition will be automatically applied",
    note2_edit: "* Click on the stickers to start editting",
    button1_image_edit: "Complete",
    button2_image_edit: "Back",
    button1_image_results: "Download",
    button2_image_results: "Back to edit",
    button3_image_results: "Home",
  },
  vn: {
    header: "Vui cùng",
    title1: "Con chữ",
    title2: "Hình ảnh",
    header_text: "Chơi cùng Tên",
    notename_text: "Từ 4-10 kí tự",
    notenslogan_text: "Từ 8-35 kí tự",
    slogan_text: "Lên CHUS sắm chất",
    button1_text: "Lưu và Tải về",
    button2_text: "Trang chủ",

    // image
    note1_crop: "* Thời gian tải hình sẽ phụ thuộc vào dung lượng hình",
    note2_crop: "* Khuyến nghị chọn ảnh dưới 5MB",
    header_image: "Chơi cùng Hình",
    button1_image: "Chọn hình",
    button2_image: "Trang chủ",
    button1_image_crop: "Cắt và Lưu",
    button2_image_crop: "Trang chủ",
    button3_image_crop: "Đổi hình",
    popup_edit: "CHỈNH SỬA NHÃN DÁN",
    popup1_edit: "Thêm nhãn dán",
    popup2_edit: "Xoá nhãn dán",
    note1_edit: "* Tự động nhận diện khuôn mặt",
    note2_edit: "* Nhấp vào nhãn dán để bắt đầu chỉnh sửa hoặc xoá",
    button1_image_edit: "Hoàn thành",
    button2_image_edit: "Trở về",
    button1_image_results: "Tải về",
    button2_image_results: "Trở về chỉnh sửa",
    button3_image_results: "Trang chủ",
  },
};
